version: '3'
services:

  db:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - 5432:5432
    volumes:
      - ./data2:/var/lib/postgresql/data
    networks:
      - omer-network  

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=your_email@example.com
      - PGADMIN_DEFAULT_PASSWORD=your_password
    depends_on:
      - db
    networks:
      - omer-network

networks:
  omer-network: 
    name: omer-network
    driver: bridge
